backend:
  name: git-gateway
  branch: develop
  repo: https://github.com/hubmapconsortium/ccf-releases
#local_backend: true
#publish_mode: editorial_workflow
media_folder: "static/data/uploads/"
public_folder: "/images/uploads"
site_url: https://hra-releases.netlify.app

collections:

  - name: "hra-releases"
    label: "HRA Releases"
    folder: "content/hra-releases"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/releases.njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }


  - name: "individuals"
    label: "Individuals"
    folder: "content/individuals"
    create: true
    fields:
    - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/individual.njk" }
    - label: "Individual"
      name: "individual"
      widget: "object"
      summary: "{{fields.first_name}}.{{fields.last_name}}"
      collapsed: true
      fields:
      - {label: "First Name", name: "first_name", widget: "string"}
      - {label: "Middle Name", name: "middle_name", widget: "string", required: false}
      - {label: "Last Name", name: "last_name", widget: "string"}
      - {label: "ORCID", name: "orcid",widget: "string",hint: "16 digit ORCID",pattern: ['([0-9]{4})+(-)+([0-9]{4})+(-)+([0-9]{4})+(-)+([X-X0-9]{4})',"ORCID must be a 16 digit number with no alphabets except X"]}
    identifier_field:  individual.last_name
    slug: "{{individual.first_name}}.{{individual.last_name}}"


  - name: "digital-object-types"
    label: "Digital Object Types"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/model.njk" }
      - { label: "Model Type", name: "type", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
    identifier_field: type
    folder: "content/digital-object-types"
    
    
  - name: "digital-objects"
    label: "Digital Object"
    label_singular: "Digital Object"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Digital Object Version", name: "release_version", widget: "select", options: [ { label: "v1.0", value: "v1.0" }, { label: "v1.1", value: "v1.1" }, { label: "v1.2", value: "v1.2" }, { label: "v1.3", value: "v1.3" }, { label: "v1.4", value: "v1.4" }, { label: "v1.5", value: "v1.5" }, { label: "v1.6", value: "v1.6" }, {label: "v1.7",  value: "v1.7" } ] }
      - { label: "HRA Releases", name: "hra_release_version",  widget: "list", allow_add: true, collapsed: true, field: {
          label: "HRA Release" , name: "hra_releases", widget: "relation", summary: "{{ fields.hra_release_versions }}", search_fields: ["title"],display_fields: ["title"],collection: "hra-releases", value_field: "title" },collection: "hra-releases", options_length: 100, 
        }
      - { label: "Digital Object Type", name: "type", widget: "relation", collection: "digital-object-types", search_fields: ["type"], value_field: "type", display_fields: ["type"]}
      - { label: "Description", name: "description", widget: "markdown"}
      - { label: "Creator(s)", name: "creators", widget: "list", allow_add: true, collapsed: true, field: {label: "Creator", name: "creator", widget: "relation", collection: "individuals",collapsed: true, summary: "{{fields.creator}}", search_fields: ["individual.orcid"], value_field: "individual.orcid",display_fields: ["individual.first_name","individual.last_name","individual.orcid"],options_length: 100  }}

      - { label: "Project Lead(s)", name: "project_leads", widget: "list", allow_add: true, collapsed: true,field: {label: "Project Lead", name: "project_lead", widget: "relation",collection: "individuals", search_fields: ["individual.orcid"], value_field: "individual.orcid",display_fields: ["individual.first_name","individual.last_name","individual.orcid"],options_length: 100  }  } 
      - { label: "Internal Reviewers(s)", name: "internal_reviewers", widget: "list", allow_add: true, collapsed: true, field: {label: "Internal Reviewer", name: "internal_reviewer", widget: "relation", collection: "individuals", search_fields: ["individual.orcid"], value_field: "individual.orcid",display_fields: ["individual.first_name","individual.last_name","individual.orcid"],options_length: 100   }}
      - { label: "External Reviewers(s)", name: "external_reviewers", widget: "list", allow_add: true, collapsed: true, field: {label: "External Reviewer", name: "external_reviewer", widget: "relation", collection: "individuals", search_fields: ["individual.orcid"], value_field: "individual.orcid",display_fields: ["individual.first_name","individual.last_name","individual.orcid"],options_length: 100   }}
      - { label: "Creation Date", name: "creation_date", widget: "date", default: "", format: "YYYY-MM-DD"}
      - { label: "License", name: "license", widget: "select",options: [
        { label: "Creative Commons Attribution 4.0 International (CC BY 4.0)", value: "CC BY 4.0" },
        { label: "MIT", value: "MIT"}]
        }
      - { label: "Publisher", name: "publisher", widget: "string"}
      - { label: "Funder", name: "funder", widget: "string"}
      - { label: "Award Number", name: "award_number", widget: "string"}
      - { label: "HuBMAP ID", name: "hubmap_id", widget: "string"}
      - { label: "Data Table", name: "datatable", widget: "file",media_library: {media_folder: "../data/uploads/"}}
      - { label: "DOI", name: "doi", widget: "string"}
    identifier_field: title
    folder: "content/digital-objects"  
    slug: "{{title}}"
    path: "{{release_version}}/docs/{{model_type}}/{{slug}}"
